import { Shipment, DisruptionScenario } from "./types";

// ─── SHIPMENTS ─────────────────────────────────────────────────────────────────
// 45 shipments across 5 geographic clusters + baseline

export const shipments: Shipment[] = [
  // ═══ GULF COAST CLUSTER (8 shipments) — Hurricane scenario ═══
  {
    id: "SHP-2024-0801",
    clientName: "Texas Petroleum Holdings",
    origin: { lat: 38.627, lng: -90.199, label: "St. Louis, MO" },
    destination: { lat: 29.76, lng: -95.37, label: "Houston, TX" },
    currentLocation: { lat: 30.332, lng: -91.104, label: "Baton Rouge, LA" },
    status: "in-transit",
    cargoType: "Network Infrastructure",
    cargoDescription: "48x Cisco Catalyst 9300 switches + cabling kits",
    value: 234000,
    weight: 3200,
    routeType: "ground",
    carrier: "XPO Logistics",
    estimatedDelivery: "2024-10-28",
    integrationCenter: "St. Louis",
    waypoints: [
      { lat: 36.163, lng: -86.782, label: "Memphis, TN" },
      { lat: 32.299, lng: -90.185, label: "Jackson, MS" },
      { lat: 30.332, lng: -91.104, label: "Baton Rouge, LA" },
    ],
    priority: "expedited",
    projectId: "PRJ-TPH-2024-Q4",
  },
  {
    id: "SHP-2024-0802",
    clientName: "Southeastern University System",
    origin: { lat: 38.627, lng: -90.199, label: "St. Louis, MO" },
    destination: { lat: 25.761, lng: -80.192, label: "Miami, FL" },
    currentLocation: { lat: 30.455, lng: -84.253, label: "Tallahassee, FL" },
    status: "in-transit",
    cargoType: "Server Rack",
    cargoDescription: "8x HPE ProLiant DL380 Gen11 servers + UPS units",
    value: 520000,
    weight: 6800,
    routeType: "ground",
    carrier: "FedEx Freight",
    estimatedDelivery: "2024-10-30",
    integrationCenter: "St. Louis",
    waypoints: [
      { lat: 33.749, lng: -84.388, label: "Atlanta, GA" },
      { lat: 30.455, lng: -84.253, label: "Tallahassee, FL" },
      { lat: 28.538, lng: -81.379, label: "Orlando, FL" },
    ],
    priority: "critical",
    projectId: "PRJ-SUS-2024-Q3",
  },
  {
    id: "SHP-2024-0803",
    clientName: "Gulf States Medical Center",
    origin: { lat: 38.627, lng: -90.199, label: "St. Louis, MO" },
    destination: { lat: 29.951, lng: -90.072, label: "New Orleans, LA" },
    currentLocation: { lat: 34.746, lng: -92.29, label: "Little Rock, AR" },
    status: "in-transit",
    cargoType: "Data Center Hardware",
    cargoDescription: "Complete micro data center pod: 4x racks + cooling",
    value: 1850000,
    weight: 22000,
    routeType: "ground",
    carrier: "XPO Logistics",
    estimatedDelivery: "2024-11-02",
    integrationCenter: "St. Louis",
    waypoints: [
      { lat: 34.746, lng: -92.29, label: "Little Rock, AR" },
      { lat: 32.351, lng: -90.878, label: "Vicksburg, MS" },
    ],
    priority: "critical",
    projectId: "PRJ-GSM-2024-Q4",
  },
  {
    id: "SHP-2024-0804",
    clientName: "Coastal Energy Partners",
    origin: { lat: 32.777, lng: -96.797, label: "Dallas, TX" },
    destination: { lat: 27.801, lng: -97.396, label: "Corpus Christi, TX" },
    currentLocation: { lat: 29.424, lng: -98.494, label: "San Antonio, TX" },
    status: "in-transit",
    cargoType: "Security Appliances",
    cargoDescription: "12x Palo Alto PA-5260 firewalls + Panorama appliance",
    value: 380000,
    weight: 1800,
    routeType: "ground",
    carrier: "UPS Supply Chain",
    estimatedDelivery: "2024-10-27",
    integrationCenter: "St. Louis",
    waypoints: [
      { lat: 30.267, lng: -97.743, label: "Austin, TX" },
      { lat: 29.424, lng: -98.494, label: "San Antonio, TX" },
    ],
    priority: "standard",
    projectId: "PRJ-CEP-2024-Q4",
  },
  {
    id: "SHP-2024-0805",
    clientName: "Florida Health Network",
    origin: { lat: 38.627, lng: -90.199, label: "St. Louis, MO" },
    destination: { lat: 27.951, lng: -82.458, label: "Tampa, FL" },
    currentLocation: { lat: 31.209, lng: -85.362, label: "Dothan, AL" },
    status: "in-transit",
    cargoType: "AV/Collaboration",
    cargoDescription: "24x Cisco Webex Board Pro 75\" + room systems",
    value: 412000,
    weight: 4500,
    routeType: "ground",
    carrier: "FedEx Freight",
    estimatedDelivery: "2024-10-31",
    integrationCenter: "St. Louis",
    waypoints: [
      { lat: 33.52, lng: -86.803, label: "Birmingham, AL" },
      { lat: 31.209, lng: -85.362, label: "Dothan, AL" },
    ],
    priority: "expedited",
    projectId: "PRJ-FHN-2024-Q3",
  },
  {
    id: "SHP-2024-0806",
    clientName: "Texas Petroleum Holdings",
    origin: { lat: 38.627, lng: -90.199, label: "St. Louis, MO" },
    destination: { lat: 30.267, lng: -97.743, label: "Austin, TX" },
    currentLocation: { lat: 32.467, lng: -93.714, label: "Shreveport, LA" },
    status: "delayed",
    cargoType: "Storage Array",
    cargoDescription: "4x NetApp AFF A900 all-flash arrays",
    value: 2100000,
    weight: 8400,
    routeType: "ground",
    carrier: "CEVA Logistics",
    estimatedDelivery: "2024-10-25",
    integrationCenter: "St. Louis",
    waypoints: [
      { lat: 35.149, lng: -90.049, label: "Memphis, TN" },
      { lat: 32.467, lng: -93.714, label: "Shreveport, LA" },
      { lat: 32.777, lng: -96.797, label: "Dallas, TX" },
    ],
    priority: "critical",
    projectId: "PRJ-TPH-2024-Q3",
  },
  {
    id: "SHP-2024-0807",
    clientName: "Southern Cross Mining Ltd",
    origin: { lat: 29.76, lng: -95.37, label: "Houston, TX" },
    destination: { lat: 30.396, lng: -88.885, label: "Mobile, AL" },
    currentLocation: { lat: 30.224, lng: -92.019, label: "Lake Charles, LA" },
    status: "in-transit",
    cargoType: "Network Infrastructure",
    cargoDescription: "16x Aruba CX 6400 switches + AP-635 access points",
    value: 178000,
    weight: 1400,
    routeType: "ground",
    carrier: "XPO Logistics",
    estimatedDelivery: "2024-10-29",
    integrationCenter: "St. Louis",
    waypoints: [
      { lat: 30.224, lng: -92.019, label: "Lake Charles, LA" },
      { lat: 30.227, lng: -90.113, label: "Gonzales, LA" },
    ],
    priority: "standard",
    projectId: "PRJ-SCM-2024-Q4",
  },
  {
    id: "SHP-2024-0808",
    clientName: "Gulf States Medical Center",
    origin: { lat: 38.627, lng: -90.199, label: "St. Louis, MO" },
    destination: { lat: 30.332, lng: -81.656, label: "Jacksonville, FL" },
    currentLocation: { lat: 33.749, lng: -84.388, label: "Atlanta, GA" },
    status: "staging",
    cargoType: "Server Rack",
    cargoDescription: "6x Dell PowerEdge R760 servers + VMware licensing",
    value: 675000,
    weight: 5200,
    routeType: "ground",
    carrier: "FedEx Freight",
    estimatedDelivery: "2024-11-05",
    integrationCenter: "St. Louis",
    waypoints: [
      { lat: 36.163, lng: -86.782, label: "Nashville, TN" },
      { lat: 33.749, lng: -84.388, label: "Atlanta, GA" },
    ],
    priority: "expedited",
    projectId: "PRJ-GSM-2024-Q4b",
  },

  // ═══ SUEZ CANAL CLUSTER (7 shipments) — Blockage scenario ═══
  {
    id: "SHP-2024-0811",
    clientName: "Midwest Health Systems",
    origin: { lat: 31.23, lng: 121.474, label: "Shanghai, CN" },
    destination: { lat: 38.627, lng: -90.199, label: "St. Louis, MO" },
    currentLocation: { lat: 29.951, lng: 32.55, label: "Suez Canal, EG" },
    status: "in-transit",
    cargoType: "Server Rack",
    cargoDescription: "12x Dell PowerEdge R760 servers + rail kits",
    value: 847000,
    weight: 14200,
    routeType: "ocean",
    carrier: "Maersk",
    estimatedDelivery: "2024-11-15",
    integrationCenter: "St. Louis",
    waypoints: [
      { lat: 1.352, lng: 103.82, label: "Singapore Strait" },
      { lat: 12.88, lng: 45.036, label: "Gulf of Aden" },
      { lat: 29.951, lng: 32.55, label: "Suez Canal" },
      { lat: 35.899, lng: -5.303, label: "Strait of Gibraltar" },
      { lat: 40.689, lng: -74.045, label: "New York Harbor" },
    ],
    priority: "critical",
    projectId: "PRJ-MHS-2024-Q3",
  },
  {
    id: "SHP-2024-0812",
    clientName: "Nordic Telecom AB",
    origin: { lat: 22.543, lng: 114.058, label: "Shenzhen, CN" },
    destination: { lat: 52.37, lng: 4.895, label: "Amsterdam, NL" },
    currentLocation: { lat: 12.88, lng: 45.036, label: "Gulf of Aden" },
    status: "in-transit",
    cargoType: "Network Infrastructure",
    cargoDescription: "200x Juniper EX4650 switches for 5G backbone",
    value: 3200000,
    weight: 18000,
    routeType: "ocean",
    carrier: "MSC",
    estimatedDelivery: "2024-11-20",
    integrationCenter: "Amsterdam",
    waypoints: [
      { lat: 1.352, lng: 103.82, label: "Singapore Strait" },
      { lat: 12.88, lng: 45.036, label: "Gulf of Aden" },
      { lat: 29.951, lng: 32.55, label: "Suez Canal" },
      { lat: 37.943, lng: 23.643, label: "Piraeus, GR" },
      { lat: 51.904, lng: 4.493, label: "Rotterdam, NL" },
    ],
    priority: "critical",
    projectId: "PRJ-NTE-2024-Q4",
  },
  {
    id: "SHP-2024-0813",
    clientName: "Great Lakes Financial Corp",
    origin: { lat: 35.682, lng: 139.691, label: "Tokyo, JP" },
    destination: { lat: 52.37, lng: 4.895, label: "Amsterdam, NL" },
    currentLocation: { lat: 1.352, lng: 103.82, label: "Singapore" },
    status: "in-transit",
    cargoType: "Storage Array",
    cargoDescription: "8x Pure Storage FlashArray//X70 R4",
    value: 1450000,
    weight: 7200,
    routeType: "ocean",
    carrier: "Maersk",
    estimatedDelivery: "2024-11-25",
    integrationCenter: "Amsterdam",
    waypoints: [
      { lat: 22.284, lng: 114.158, label: "Hong Kong" },
      { lat: 1.352, lng: 103.82, label: "Singapore" },
      { lat: 12.88, lng: 45.036, label: "Gulf of Aden" },
      { lat: 29.951, lng: 32.55, label: "Suez Canal" },
      { lat: 51.904, lng: 4.493, label: "Rotterdam, NL" },
    ],
    priority: "expedited",
    projectId: "PRJ-GLF-2024-Q4",
  },
  {
    id: "SHP-2024-0814",
    clientName: "Atlantic Defense Solutions",
    origin: { lat: 1.352, lng: 103.82, label: "Singapore" },
    destination: { lat: 38.627, lng: -90.199, label: "St. Louis, MO" },
    currentLocation: { lat: 15.963, lng: 56.27, label: "Arabian Sea" },
    status: "in-transit",
    cargoType: "Security Appliances",
    cargoDescription: "24x Fortinet FG-3700F + FortiManager 1000F",
    value: 920000,
    weight: 3600,
    routeType: "ocean",
    carrier: "Hapag-Lloyd",
    estimatedDelivery: "2024-11-18",
    integrationCenter: "St. Louis",
    waypoints: [
      { lat: 12.88, lng: 45.036, label: "Gulf of Aden" },
      { lat: 29.951, lng: 32.55, label: "Suez Canal" },
      { lat: 35.899, lng: -5.303, label: "Strait of Gibraltar" },
      { lat: 36.848, lng: -76.292, label: "Norfolk, VA" },
    ],
    priority: "critical",
    projectId: "PRJ-ADS-2024-Q4",
  },
  {
    id: "SHP-2024-0815",
    clientName: "Commonwealth Retail Partners",
    origin: { lat: 22.543, lng: 114.058, label: "Shenzhen, CN" },
    destination: { lat: 52.37, lng: 4.895, label: "Amsterdam, NL" },
    currentLocation: { lat: 35.899, lng: -5.303, label: "Strait of Gibraltar" },
    status: "in-transit",
    cargoType: "AV/Collaboration",
    cargoDescription: "150x digital signage displays + media players",
    value: 385000,
    weight: 9500,
    routeType: "ocean",
    carrier: "MSC",
    estimatedDelivery: "2024-11-08",
    integrationCenter: "Amsterdam",
    waypoints: [
      { lat: 1.352, lng: 103.82, label: "Singapore Strait" },
      { lat: 12.88, lng: 45.036, label: "Gulf of Aden" },
      { lat: 29.951, lng: 32.55, label: "Suez Canal" },
      { lat: 35.899, lng: -5.303, label: "Strait of Gibraltar" },
    ],
    priority: "standard",
    projectId: "PRJ-CRP-2024-Q4",
  },
  {
    id: "SHP-2024-0816",
    clientName: "Nordic Telecom AB",
    origin: { lat: 31.23, lng: 121.474, label: "Shanghai, CN" },
    destination: { lat: 52.37, lng: 4.895, label: "Amsterdam, NL" },
    currentLocation: { lat: 37.943, lng: 23.643, label: "Piraeus, GR" },
    status: "in-transit",
    cargoType: "Data Center Hardware",
    cargoDescription: "Complete cooling system: 20x CRAC units + piping",
    value: 780000,
    weight: 32000,
    routeType: "ocean",
    carrier: "Maersk",
    estimatedDelivery: "2024-11-10",
    integrationCenter: "Amsterdam",
    waypoints: [
      { lat: 1.352, lng: 103.82, label: "Singapore Strait" },
      { lat: 12.88, lng: 45.036, label: "Gulf of Aden" },
      { lat: 29.951, lng: 32.55, label: "Suez Canal" },
      { lat: 37.943, lng: 23.643, label: "Piraeus, GR" },
    ],
    priority: "expedited",
    projectId: "PRJ-NTE-2024-Q4b",
  },
  {
    id: "SHP-2024-0817",
    clientName: "Bay Area Transit Authority",
    origin: { lat: 35.682, lng: 139.691, label: "Tokyo, JP" },
    destination: { lat: 38.627, lng: -90.199, label: "St. Louis, MO" },
    currentLocation: { lat: 22.284, lng: 114.158, label: "Hong Kong" },
    status: "staging",
    cargoType: "Network Infrastructure",
    cargoDescription: "32x Cisco Nexus 9364C spine switches",
    value: 1680000,
    weight: 4800,
    routeType: "ocean",
    carrier: "Hapag-Lloyd",
    estimatedDelivery: "2024-12-01",
    integrationCenter: "St. Louis",
    waypoints: [
      { lat: 22.284, lng: 114.158, label: "Hong Kong" },
      { lat: 1.352, lng: 103.82, label: "Singapore" },
      { lat: 12.88, lng: 45.036, label: "Gulf of Aden" },
      { lat: 29.951, lng: 32.55, label: "Suez Canal" },
      { lat: 40.689, lng: -74.045, label: "New York Harbor" },
    ],
    priority: "critical",
    projectId: "PRJ-BAT-2024-Q4",
  },

  // ═══ WEST COAST PORT CLUSTER (7 shipments) — Port congestion scenario ═══
  {
    id: "SHP-2024-0821",
    clientName: "Silicon Valley Dynamics",
    origin: { lat: 31.23, lng: 121.474, label: "Shanghai, CN" },
    destination: { lat: 37.775, lng: -122.418, label: "San Francisco, CA" },
    currentLocation: { lat: 33.738, lng: -118.26, label: "Port of Long Beach, CA" },
    status: "in-transit",
    cargoType: "Server Rack",
    cargoDescription: "20x NVIDIA DGX A100 GPU servers",
    value: 4800000,
    weight: 16000,
    routeType: "ocean",
    carrier: "Maersk",
    estimatedDelivery: "2024-10-30",
    integrationCenter: "St. Louis",
    waypoints: [
      { lat: 35.45, lng: -155.0, label: "Pacific Ocean" },
      { lat: 33.738, lng: -118.26, label: "Port of Long Beach, CA" },
    ],
    priority: "critical",
    projectId: "PRJ-SVD-2024-Q3",
  },
  {
    id: "SHP-2024-0822",
    clientName: "Pacific Northwest Medical Group",
    origin: { lat: 22.543, lng: 114.058, label: "Shenzhen, CN" },
    destination: { lat: 47.606, lng: -122.332, label: "Seattle, WA" },
    currentLocation: { lat: 35.45, lng: -155.0, label: "Pacific Ocean" },
    status: "in-transit",
    cargoType: "Data Center Hardware",
    cargoDescription: "Complete data center pod: 8x racks, PDUs, cabling",
    value: 2350000,
    weight: 28000,
    routeType: "ocean",
    carrier: "COSCO",
    estimatedDelivery: "2024-11-05",
    integrationCenter: "St. Louis",
    waypoints: [
      { lat: 35.45, lng: -155.0, label: "Pacific Ocean" },
      { lat: 33.738, lng: -118.26, label: "Port of Los Angeles, CA" },
      { lat: 45.523, lng: -122.676, label: "Portland, OR" },
    ],
    priority: "critical",
    projectId: "PRJ-PNM-2024-Q4",
  },
  {
    id: "SHP-2024-0823",
    clientName: "Rocky Mountain Energy Partners",
    origin: { lat: 35.682, lng: 139.691, label: "Tokyo, JP" },
    destination: { lat: 39.739, lng: -104.99, label: "Denver, CO" },
    currentLocation: { lat: 33.738, lng: -118.26, label: "Port of Los Angeles, CA" },
    status: "delayed",
    cargoType: "Network Infrastructure",
    cargoDescription: "64x Cisco Meraki MR56 APs + MS390 switches",
    value: 295000,
    weight: 2800,
    routeType: "multimodal",
    carrier: "Kuehne+Nagel",
    estimatedDelivery: "2024-10-22",
    integrationCenter: "St. Louis",
    waypoints: [
      { lat: 35.45, lng: -155.0, label: "Pacific Ocean" },
      { lat: 33.738, lng: -118.26, label: "Port of Los Angeles, CA" },
      { lat: 36.17, lng: -115.14, label: "Las Vegas, NV" },
    ],
    priority: "expedited",
    projectId: "PRJ-RME-2024-Q4",
  },
  {
    id: "SHP-2024-0824",
    clientName: "Silicon Valley Dynamics",
    origin: { lat: 37.566, lng: 126.978, label: "Seoul, KR" },
    destination: { lat: 37.775, lng: -122.418, label: "San Francisco, CA" },
    currentLocation: { lat: 40.0, lng: -170.0, label: "North Pacific" },
    status: "in-transit",
    cargoType: "Storage Array",
    cargoDescription: "6x Samsung PM1733 NVMe SSD arrays",
    value: 890000,
    weight: 3200,
    routeType: "ocean",
    carrier: "MSC",
    estimatedDelivery: "2024-11-10",
    integrationCenter: "St. Louis",
    waypoints: [
      { lat: 40.0, lng: -170.0, label: "North Pacific" },
      { lat: 33.738, lng: -118.26, label: "Port of Long Beach, CA" },
    ],
    priority: "expedited",
    projectId: "PRJ-SVD-2024-Q4",
  },
  {
    id: "SHP-2024-0825",
    clientName: "Bay Area Transit Authority",
    origin: { lat: 1.352, lng: 103.82, label: "Singapore" },
    destination: { lat: 34.052, lng: -118.244, label: "Los Angeles, CA" },
    currentLocation: { lat: 21.307, lng: -157.858, label: "Honolulu, HI" },
    status: "in-transit",
    cargoType: "Security Appliances",
    cargoDescription: "36x Cisco Secure Firewall 4215 + ISE appliances",
    value: 540000,
    weight: 2100,
    routeType: "ocean",
    carrier: "Hapag-Lloyd",
    estimatedDelivery: "2024-11-12",
    integrationCenter: "St. Louis",
    waypoints: [
      { lat: 21.307, lng: -157.858, label: "Honolulu, HI" },
      { lat: 33.738, lng: -118.26, label: "Port of Los Angeles, CA" },
    ],
    priority: "standard",
    projectId: "PRJ-BAT-2024-Q3",
  },
  {
    id: "SHP-2024-0826",
    clientName: "Pacific Northwest Medical Group",
    origin: { lat: 31.23, lng: 121.474, label: "Shanghai, CN" },
    destination: { lat: 45.523, lng: -122.676, label: "Portland, OR" },
    currentLocation: { lat: 33.738, lng: -118.26, label: "Port of Long Beach, CA" },
    status: "in-transit",
    cargoType: "AV/Collaboration",
    cargoDescription: "48x Poly Studio X70 video bars + TC10 controllers",
    value: 310000,
    weight: 1800,
    routeType: "multimodal",
    carrier: "DHL Global Forwarding",
    estimatedDelivery: "2024-11-01",
    integrationCenter: "St. Louis",
    waypoints: [
      { lat: 35.45, lng: -155.0, label: "Pacific Ocean" },
      { lat: 33.738, lng: -118.26, label: "Port of Long Beach, CA" },
    ],
    priority: "standard",
    projectId: "PRJ-PNM-2024-Q3",
  },
  {
    id: "SHP-2024-0827",
    clientName: "Heartland Insurance Group",
    origin: { lat: 22.543, lng: 114.058, label: "Shenzhen, CN" },
    destination: { lat: 41.878, lng: -87.63, label: "Chicago, IL" },
    currentLocation: { lat: 33.738, lng: -118.26, label: "Port of Los Angeles, CA" },
    status: "staging",
    cargoType: "Server Rack",
    cargoDescription: "16x Lenovo ThinkSystem SR670 V2 + GPU cards",
    value: 1230000,
    weight: 12000,
    routeType: "multimodal",
    carrier: "COSCO",
    estimatedDelivery: "2024-11-08",
    integrationCenter: "St. Louis",
    waypoints: [
      { lat: 35.45, lng: -155.0, label: "Pacific Ocean" },
      { lat: 33.738, lng: -118.26, label: "Port of Los Angeles, CA" },
      { lat: 34.052, lng: -118.244, label: "Los Angeles, CA" },
    ],
    priority: "expedited",
    projectId: "PRJ-HIG-2024-Q4",
  },

  // ═══ MIDWEST CLUSTER (7 shipments) — Winter storm scenario ═══
  {
    id: "SHP-2024-0831",
    clientName: "Heartland Insurance Group",
    origin: { lat: 40.689, lng: -74.045, label: "Newark, NJ" },
    destination: { lat: 38.627, lng: -90.199, label: "St. Louis, MO" },
    currentLocation: { lat: 39.962, lng: -82.999, label: "Columbus, OH" },
    status: "in-transit",
    cargoType: "Network Infrastructure",
    cargoDescription: "24x Arista 7280R3 spine switches + optics",
    value: 560000,
    weight: 3400,
    routeType: "ground",
    carrier: "XPO Logistics",
    estimatedDelivery: "2024-10-29",
    integrationCenter: "St. Louis",
    waypoints: [
      { lat: 40.441, lng: -79.995, label: "Pittsburgh, PA" },
      { lat: 39.962, lng: -82.999, label: "Columbus, OH" },
      { lat: 39.768, lng: -86.158, label: "Indianapolis, IN" },
    ],
    priority: "expedited",
    projectId: "PRJ-HIG-2024-Q3",
  },
  {
    id: "SHP-2024-0832",
    clientName: "Midwest Health Systems",
    origin: { lat: 41.878, lng: -87.63, label: "Chicago, IL" },
    destination: { lat: 38.627, lng: -90.199, label: "St. Louis, MO" },
    currentLocation: { lat: 40.484, lng: -88.994, label: "Bloomington, IL" },
    status: "in-transit",
    cargoType: "Data Center Hardware",
    cargoDescription: "3x Schneider Electric Galaxy VX UPS + batteries",
    value: 430000,
    weight: 18000,
    routeType: "ground",
    carrier: "FedEx Freight",
    estimatedDelivery: "2024-10-27",
    integrationCenter: "St. Louis",
    waypoints: [
      { lat: 40.484, lng: -88.994, label: "Bloomington, IL" },
      { lat: 39.801, lng: -89.644, label: "Springfield, IL" },
    ],
    priority: "critical",
    projectId: "PRJ-MHS-2024-Q4",
  },
  {
    id: "SHP-2024-0833",
    clientName: "Great Lakes Financial Corp",
    origin: { lat: 42.331, lng: -83.046, label: "Detroit, MI" },
    destination: { lat: 38.627, lng: -90.199, label: "St. Louis, MO" },
    currentLocation: { lat: 41.878, lng: -87.63, label: "Chicago, IL" },
    status: "in-transit",
    cargoType: "Security Appliances",
    cargoDescription: "8x CrowdStrike Falcon appliances + 500 licenses",
    value: 340000,
    weight: 1200,
    routeType: "ground",
    carrier: "UPS Supply Chain",
    estimatedDelivery: "2024-10-28",
    integrationCenter: "St. Louis",
    waypoints: [
      { lat: 41.878, lng: -87.63, label: "Chicago, IL" },
      { lat: 39.801, lng: -89.644, label: "Springfield, IL" },
    ],
    priority: "standard",
    projectId: "PRJ-GLF-2024-Q3",
  },
  {
    id: "SHP-2024-0834",
    clientName: "Rocky Mountain Energy Partners",
    origin: { lat: 44.978, lng: -93.265, label: "Minneapolis, MN" },
    destination: { lat: 38.627, lng: -90.199, label: "St. Louis, MO" },
    currentLocation: { lat: 42.034, lng: -93.62, label: "Ames, IA" },
    status: "in-transit",
    cargoType: "Server Rack",
    cargoDescription: "10x Dell PowerEdge MX7000 chassis + blades",
    value: 780000,
    weight: 8600,
    routeType: "ground",
    carrier: "CEVA Logistics",
    estimatedDelivery: "2024-10-30",
    integrationCenter: "St. Louis",
    waypoints: [
      { lat: 42.034, lng: -93.62, label: "Ames, IA" },
      { lat: 41.262, lng: -95.861, label: "Omaha, NE" },
      { lat: 39.099, lng: -94.578, label: "Kansas City, MO" },
    ],
    priority: "expedited",
    projectId: "PRJ-RME-2024-Q3",
  },
  {
    id: "SHP-2024-0835",
    clientName: "Commonwealth Retail Partners",
    origin: { lat: 39.962, lng: -82.999, label: "Columbus, OH" },
    destination: { lat: 39.099, lng: -94.578, label: "Kansas City, MO" },
    currentLocation: { lat: 39.768, lng: -86.158, label: "Indianapolis, IN" },
    status: "in-transit",
    cargoType: "AV/Collaboration",
    cargoDescription: "200x Crestron Flex UC systems for retail locations",
    value: 650000,
    weight: 5400,
    routeType: "ground",
    carrier: "FedEx Freight",
    estimatedDelivery: "2024-10-31",
    integrationCenter: "St. Louis",
    waypoints: [
      { lat: 39.768, lng: -86.158, label: "Indianapolis, IN" },
      { lat: 38.627, lng: -90.199, label: "St. Louis, MO" },
    ],
    priority: "standard",
    projectId: "PRJ-CRP-2024-Q3",
  },
  {
    id: "SHP-2024-0836",
    clientName: "Midwest Health Systems",
    origin: { lat: 38.627, lng: -90.199, label: "St. Louis, MO" },
    destination: { lat: 41.878, lng: -87.63, label: "Chicago, IL" },
    currentLocation: { lat: 38.627, lng: -90.199, label: "St. Louis, MO" },
    status: "testing",
    cargoType: "Network Infrastructure",
    cargoDescription: "Full network refresh: 96x Cisco 9200L + 12x 9500",
    value: 890000,
    weight: 6200,
    routeType: "ground",
    carrier: "XPO Logistics",
    estimatedDelivery: "2024-11-15",
    integrationCenter: "St. Louis",
    waypoints: [
      { lat: 39.801, lng: -89.644, label: "Springfield, IL" },
    ],
    priority: "critical",
    projectId: "PRJ-MHS-2024-Q3b",
  },
  {
    id: "SHP-2024-0837",
    clientName: "Great Lakes Financial Corp",
    origin: { lat: 38.627, lng: -90.199, label: "St. Louis, MO" },
    destination: { lat: 44.978, lng: -93.265, label: "Minneapolis, MN" },
    currentLocation: { lat: 38.627, lng: -90.199, label: "St. Louis, MO" },
    status: "staging",
    cargoType: "Data Center Hardware",
    cargoDescription: "6x Vertiv Liebert CRV cooling units",
    value: 215000,
    weight: 9600,
    routeType: "ground",
    carrier: "CEVA Logistics",
    estimatedDelivery: "2024-11-18",
    integrationCenter: "St. Louis",
    waypoints: [
      { lat: 41.262, lng: -95.861, label: "Omaha, NE" },
    ],
    priority: "standard",
    projectId: "PRJ-GLF-2024-Q4b",
  },

  // ═══ SEMICONDUCTOR-DEPENDENT (6 shipments) — Parts shortage scenario ═══
  {
    id: "SHP-2024-0841",
    clientName: "Silicon Valley Dynamics",
    origin: { lat: 37.389, lng: -122.083, label: "Santa Clara, CA" },
    destination: { lat: 38.627, lng: -90.199, label: "St. Louis, MO" },
    currentLocation: { lat: 37.389, lng: -122.083, label: "Santa Clara, CA" },
    status: "staging",
    cargoType: "Server Rack",
    cargoDescription: "8x NVIDIA HGX H100 GPU servers — awaiting GPU allocation",
    value: 3200000,
    weight: 4800,
    routeType: "air",
    carrier: "FedEx Express",
    estimatedDelivery: "2024-11-20",
    integrationCenter: "St. Louis",
    waypoints: [
      { lat: 39.849, lng: -104.674, label: "Denver Hub" },
    ],
    priority: "critical",
    projectId: "PRJ-SVD-2024-Q3b",
  },
  {
    id: "SHP-2024-0842",
    clientName: "Atlantic Defense Solutions",
    origin: { lat: 38.627, lng: -90.199, label: "St. Louis, MO" },
    destination: { lat: 38.907, lng: -77.037, label: "Washington, DC" },
    currentLocation: { lat: 38.627, lng: -90.199, label: "St. Louis, MO" },
    status: "testing",
    cargoType: "Server Rack",
    cargoDescription: "4x classified compute nodes — pending chip verification",
    value: 1800000,
    weight: 3200,
    routeType: "air",
    carrier: "UPS Supply Chain",
    estimatedDelivery: "2024-11-10",
    integrationCenter: "St. Louis",
    waypoints: [
      { lat: 39.099, lng: -94.578, label: "Kansas City Hub" },
    ],
    priority: "critical",
    projectId: "PRJ-ADS-2024-Q3",
  },
  {
    id: "SHP-2024-0843",
    clientName: "Midwest Health Systems",
    origin: { lat: 37.389, lng: -122.083, label: "Santa Clara, CA" },
    destination: { lat: 38.627, lng: -90.199, label: "St. Louis, MO" },
    currentLocation: { lat: 37.389, lng: -122.083, label: "Santa Clara, CA" },
    status: "staging",
    cargoType: "Network Infrastructure",
    cargoDescription: "48x Cisco Nexus 9364D-GX2A — semiconductor constrained",
    value: 960000,
    weight: 4200,
    routeType: "air",
    carrier: "DHL Global Forwarding",
    estimatedDelivery: "2024-12-05",
    integrationCenter: "St. Louis",
    waypoints: [
      { lat: 39.849, lng: -104.674, label: "Denver Hub" },
    ],
    priority: "expedited",
    projectId: "PRJ-MHS-2024-Q4b",
  },
  {
    id: "SHP-2024-0844",
    clientName: "Bay Area Transit Authority",
    origin: { lat: 37.389, lng: -122.083, label: "Santa Clara, CA" },
    destination: { lat: 37.775, lng: -122.418, label: "San Francisco, CA" },
    currentLocation: { lat: 37.389, lng: -122.083, label: "Santa Clara, CA" },
    status: "testing",
    cargoType: "Network Infrastructure",
    cargoDescription: "16x Arista 7800R3 chassis — custom ASIC dependent",
    value: 2400000,
    weight: 6400,
    routeType: "ground",
    carrier: "Local Delivery",
    estimatedDelivery: "2024-11-15",
    integrationCenter: "St. Louis",
    waypoints: [],
    priority: "critical",
    projectId: "PRJ-BAT-2024-Q4b",
  },
  {
    id: "SHP-2024-0845",
    clientName: "Nordic Telecom AB",
    origin: { lat: 52.37, lng: 4.895, label: "Amsterdam, NL" },
    destination: { lat: 59.329, lng: 18.069, label: "Stockholm, SE" },
    currentLocation: { lat: 52.37, lng: 4.895, label: "Amsterdam, NL" },
    status: "staging",
    cargoType: "Server Rack",
    cargoDescription: "24x AMD EPYC 9654 servers — processor allocation pending",
    value: 1560000,
    weight: 8800,
    routeType: "ground",
    carrier: "DHL Freight",
    estimatedDelivery: "2024-11-25",
    integrationCenter: "Amsterdam",
    waypoints: [
      { lat: 53.551, lng: 9.994, label: "Hamburg, DE" },
      { lat: 55.676, lng: 12.569, label: "Copenhagen, DK" },
    ],
    priority: "expedited",
    projectId: "PRJ-NTE-2024-Q3",
  },
  {
    id: "SHP-2024-0846",
    clientName: "Heartland Insurance Group",
    origin: { lat: 38.627, lng: -90.199, label: "St. Louis, MO" },
    destination: { lat: 39.962, lng: -82.999, label: "Columbus, OH" },
    currentLocation: { lat: 38.627, lng: -90.199, label: "St. Louis, MO" },
    status: "testing",
    cargoType: "Data Center Hardware",
    cargoDescription: "SmartNIC upgrade: 100x NVIDIA ConnectX-7 adapters",
    value: 450000,
    weight: 500,
    routeType: "air",
    carrier: "FedEx Express",
    estimatedDelivery: "2024-11-08",
    integrationCenter: "St. Louis",
    waypoints: [],
    priority: "standard",
    projectId: "PRJ-HIG-2024-Q4b",
  },

  // ═══ UNAFFECTED BASELINE (10 shipments) ═══
  {
    id: "SHP-2024-0851",
    clientName: "Commonwealth Retail Partners",
    origin: { lat: 52.37, lng: 4.895, label: "Amsterdam, NL" },
    destination: { lat: 51.507, lng: -0.128, label: "London, UK" },
    currentLocation: { lat: 51.927, lng: 4.479, label: "Hook of Holland, NL" },
    status: "in-transit",
    cargoType: "AV/Collaboration",
    cargoDescription: "80x Samsung Flip Pro 85\" interactive displays",
    value: 240000,
    weight: 6400,
    routeType: "multimodal",
    carrier: "DHL Freight",
    estimatedDelivery: "2024-10-26",
    integrationCenter: "Amsterdam",
    waypoints: [
      { lat: 51.927, lng: 4.479, label: "Hook of Holland, NL" },
      { lat: 51.353, lng: 1.108, label: "Dover, UK" },
    ],
    priority: "standard",
    projectId: "PRJ-CRP-2024-Q3b",
  },
  {
    id: "SHP-2024-0852",
    clientName: "Atlantic Defense Solutions",
    origin: { lat: 38.627, lng: -90.199, label: "St. Louis, MO" },
    destination: { lat: 38.907, lng: -77.037, label: "Washington, DC" },
    currentLocation: { lat: 37.54, lng: -77.436, label: "Richmond, VA" },
    status: "in-transit",
    cargoType: "Security Appliances",
    cargoDescription: "16x Juniper SRX5800 firewalls + Junos Space",
    value: 720000,
    weight: 4200,
    routeType: "air",
    carrier: "FedEx Express",
    estimatedDelivery: "2024-10-26",
    integrationCenter: "St. Louis",
    waypoints: [
      { lat: 37.54, lng: -77.436, label: "Richmond, VA" },
    ],
    priority: "critical",
    projectId: "PRJ-ADS-2024-Q3b",
  },
  {
    id: "SHP-2024-0853",
    clientName: "Southeastern University System",
    origin: { lat: 33.749, lng: -84.388, label: "Atlanta, GA" },
    destination: { lat: 35.227, lng: -80.843, label: "Charlotte, NC" },
    currentLocation: { lat: 34.223, lng: -83.869, label: "Cornelia, GA" },
    status: "in-transit",
    cargoType: "Network Infrastructure",
    cargoDescription: "32x Extreme Networks 5520 switches + AP5050",
    value: 185000,
    weight: 2100,
    routeType: "ground",
    carrier: "UPS Supply Chain",
    estimatedDelivery: "2024-10-27",
    integrationCenter: "St. Louis",
    waypoints: [
      { lat: 34.852, lng: -82.394, label: "Greenville, SC" },
    ],
    priority: "standard",
    projectId: "PRJ-SUS-2024-Q4",
  },
  {
    id: "SHP-2024-0854",
    clientName: "Southern Cross Mining Ltd",
    origin: { lat: 1.352, lng: 103.82, label: "Singapore" },
    destination: { lat: -33.868, lng: 151.207, label: "Sydney, AU" },
    currentLocation: { lat: -12.463, lng: 130.842, label: "Darwin, AU" },
    status: "in-transit",
    cargoType: "Data Center Hardware",
    cargoDescription: "Edge computing pods: 6x ruggedized micro racks",
    value: 950000,
    weight: 3600,
    routeType: "ocean",
    carrier: "Maersk",
    estimatedDelivery: "2024-11-08",
    integrationCenter: "Singapore",
    waypoints: [
      { lat: -12.463, lng: 130.842, label: "Darwin, AU" },
      { lat: -23.856, lng: 151.256, label: "Gladstone, AU" },
    ],
    priority: "expedited",
    projectId: "PRJ-SCM-2024-Q3",
  },
  {
    id: "SHP-2024-0855",
    clientName: "Nordic Telecom AB",
    origin: { lat: 52.37, lng: 4.895, label: "Amsterdam, NL" },
    destination: { lat: 60.169, lng: 24.938, label: "Helsinki, FI" },
    currentLocation: { lat: 55.676, lng: 12.569, label: "Copenhagen, DK" },
    status: "in-transit",
    cargoType: "Network Infrastructure",
    cargoDescription: "100x Nokia Fastmile 5G gateways",
    value: 420000,
    weight: 3200,
    routeType: "ground",
    carrier: "DHL Freight",
    estimatedDelivery: "2024-11-02",
    integrationCenter: "Amsterdam",
    waypoints: [
      { lat: 53.551, lng: 9.994, label: "Hamburg, DE" },
      { lat: 55.676, lng: 12.569, label: "Copenhagen, DK" },
      { lat: 59.329, lng: 18.069, label: "Stockholm, SE" },
    ],
    priority: "standard",
    projectId: "PRJ-NTE-2024-Q4c",
  },
  {
    id: "SHP-2024-0856",
    clientName: "Southern Cross Mining Ltd",
    origin: { lat: 1.352, lng: 103.82, label: "Singapore" },
    destination: { lat: -6.208, lng: 106.846, label: "Jakarta, ID" },
    currentLocation: { lat: 1.352, lng: 103.82, label: "Singapore" },
    status: "shipped",
    cargoType: "Security Appliances",
    cargoDescription: "20x Palo Alto PA-460 + Prisma Access licenses",
    value: 165000,
    weight: 800,
    routeType: "ocean",
    carrier: "Regional Carrier",
    estimatedDelivery: "2024-10-24",
    integrationCenter: "Singapore",
    waypoints: [],
    priority: "standard",
    projectId: "PRJ-SCM-2024-Q4b",
  },
  {
    id: "SHP-2024-0857",
    clientName: "Florida Health Network",
    origin: { lat: 40.689, lng: -74.045, label: "Newark, NJ" },
    destination: { lat: 42.361, lng: -71.058, label: "Boston, MA" },
    currentLocation: { lat: 41.308, lng: -72.928, label: "New Haven, CT" },
    status: "in-transit",
    cargoType: "Storage Array",
    cargoDescription: "2x NetApp FAS9500 hybrid arrays",
    value: 380000,
    weight: 5600,
    routeType: "ground",
    carrier: "XPO Logistics",
    estimatedDelivery: "2024-10-27",
    integrationCenter: "St. Louis",
    waypoints: [
      { lat: 41.308, lng: -72.928, label: "New Haven, CT" },
      { lat: 41.824, lng: -71.413, label: "Providence, RI" },
    ],
    priority: "expedited",
    projectId: "PRJ-FHN-2024-Q4",
  },
  {
    id: "SHP-2024-0858",
    clientName: "Midwest Health Systems",
    origin: { lat: 38.627, lng: -90.199, label: "St. Louis, MO" },
    destination: { lat: 39.768, lng: -86.158, label: "Indianapolis, IN" },
    currentLocation: { lat: 38.627, lng: -90.199, label: "St. Louis, MO" },
    status: "shipped",
    cargoType: "AV/Collaboration",
    cargoDescription: "12x Cisco Room Kit EQ + Webex boards",
    value: 156000,
    weight: 1400,
    routeType: "ground",
    carrier: "Local Delivery",
    estimatedDelivery: "2024-10-25",
    integrationCenter: "St. Louis",
    waypoints: [],
    priority: "standard",
    projectId: "PRJ-MHS-2024-Q3c",
  },
  {
    id: "SHP-2024-0859",
    clientName: "Pacific Northwest Medical Group",
    origin: { lat: 47.606, lng: -122.332, label: "Seattle, WA" },
    destination: { lat: 45.523, lng: -122.676, label: "Portland, OR" },
    currentLocation: { lat: 46.602, lng: -122.903, label: "Centralia, WA" },
    status: "shipped",
    cargoType: "Network Infrastructure",
    cargoDescription: "8x Aruba CX 8360 core switches + licenses",
    value: 125000,
    weight: 600,
    routeType: "ground",
    carrier: "UPS Supply Chain",
    estimatedDelivery: "2024-10-24",
    integrationCenter: "St. Louis",
    waypoints: [],
    priority: "standard",
    projectId: "PRJ-PNM-2024-Q3b",
  },
  {
    id: "SHP-2024-0860",
    clientName: "Great Lakes Financial Corp",
    origin: { lat: 52.37, lng: 4.895, label: "Amsterdam, NL" },
    destination: { lat: 48.857, lng: 2.352, label: "Paris, FR" },
    currentLocation: { lat: 50.851, lng: 4.351, label: "Brussels, BE" },
    status: "shipped",
    cargoType: "Security Appliances",
    cargoDescription: "10x Check Point 28000 appliances + SmartConsole",
    value: 520000,
    weight: 2800,
    routeType: "ground",
    carrier: "DHL Freight",
    estimatedDelivery: "2024-10-25",
    integrationCenter: "Amsterdam",
    waypoints: [
      { lat: 50.851, lng: 4.351, label: "Brussels, BE" },
    ],
    priority: "expedited",
    projectId: "PRJ-GLF-2024-Q3b",
  },
];

// ─── DISRUPTION SCENARIOS ──────────────────────────────────────────────────────

export const scenarios: DisruptionScenario[] = [
  {
    id: "gulf-hurricane",
    name: "Gulf Coast Hurricane",
    description:
      "Category 3 hurricane making landfall on the Gulf Coast near New Orleans. Wind speeds of 120mph with storm surge warnings from Texas to Florida panhandle.",
    icon: "\u{1F300}",
    affectedRegion: {
      center: { lat: 29.0, lng: -89.0, label: "Gulf Coast" },
      radiusKm: 500,
    },
    affectedRouteSegments: [
      "gulf-coast",
      "florida-panhandle",
      "louisiana",
      "texas-coast",
    ],
    severityMultiplier: 2.5,
    estimatedDelayDays: 5,
    alternativeRoutes: [
      {
        description: "Reroute via Atlanta ground corridor",
        additionalCostPercent: 15,
        additionalDelayDays: 2,
        routeType: "ground",
      },
      {
        description: "Air freight critical items via Memphis hub",
        additionalCostPercent: 180,
        additionalDelayDays: 0,
        routeType: "air",
      },
      {
        description: "Hold at nearest staging facility until storm passes",
        additionalCostPercent: 5,
        additionalDelayDays: 5,
        routeType: "ground",
      },
    ],
    promptTemplate:
      "A Category 3 hurricane is making landfall on the Gulf Coast near New Orleans. Wind speeds of 120mph, storm surge warnings from Texas to Florida. How does this impact our active shipments and what should we do?",
  },
  {
    id: "suez-blockage",
    name: "Suez Canal Blockage",
    description:
      "A large container vessel has run aground in the Suez Canal, blocking all northbound and southbound traffic. Estimated clearance time is 7-10 days.",
    icon: "\u{1F6A2}",
    affectedRegion: {
      center: { lat: 30.0, lng: 32.5, label: "Suez Canal" },
      radiusKm: 200,
    },
    affectedRouteSegments: [
      "suez-canal",
      "red-sea",
      "gulf-of-aden",
      "mediterranean",
    ],
    severityMultiplier: 2.0,
    estimatedDelayDays: 14,
    alternativeRoutes: [
      {
        description: "Reroute via Cape of Good Hope",
        additionalCostPercent: 30,
        additionalDelayDays: 12,
        routeType: "ocean",
      },
      {
        description: "Air freight critical components",
        additionalCostPercent: 400,
        additionalDelayDays: 2,
        routeType: "air",
      },
    ],
    promptTemplate:
      "Breaking: A large container vessel has run aground in the Suez Canal, blocking all traffic. Estimated clearance time is 7-10 days. What is our exposure?",
  },
  {
    id: "port-congestion",
    name: "West Coast Port Congestion",
    description:
      "Severe congestion at the Port of Los Angeles and Long Beach. Vessel wait times have increased to 12-15 days with container dwell times exceeding 9 days.",
    icon: "\u{26F4}\u{FE0F}",
    affectedRegion: {
      center: { lat: 33.738, lng: -118.26, label: "LA/Long Beach Ports" },
      radiusKm: 150,
    },
    affectedRouteSegments: [
      "pacific-inbound",
      "la-port",
      "long-beach",
      "west-coast",
    ],
    severityMultiplier: 1.5,
    estimatedDelayDays: 10,
    alternativeRoutes: [
      {
        description: "Divert to Port of Oakland",
        additionalCostPercent: 10,
        additionalDelayDays: 3,
        routeType: "ocean",
      },
      {
        description: "Reroute to Seattle/Tacoma and ground transport south",
        additionalCostPercent: 20,
        additionalDelayDays: 5,
        routeType: "multimodal",
      },
      {
        description: "Air freight from origin for critical items",
        additionalCostPercent: 350,
        additionalDelayDays: 1,
        routeType: "air",
      },
    ],
    promptTemplate:
      "We're seeing reports of severe congestion at the Port of Los Angeles and Long Beach. Vessel wait times have increased to 12-15 days. How are our inbound shipments affected?",
  },
  {
    id: "winter-storm",
    name: "Midwest Winter Storm",
    description:
      "A severe winter storm is forecast to hit the Midwest over the next 48 hours. Blizzard conditions expected from Minneapolis through Chicago to St. Louis with highway closures likely.",
    icon: "\u{2744}\u{FE0F}",
    affectedRegion: {
      center: { lat: 40.0, lng: -89.5, label: "Central Midwest" },
      radiusKm: 600,
    },
    affectedRouteSegments: [
      "i-55",
      "i-70",
      "i-80",
      "midwest-ground",
      "chicago-hub",
      "stl-hub",
    ],
    severityMultiplier: 1.8,
    estimatedDelayDays: 4,
    alternativeRoutes: [
      {
        description: "Hold shipments at origin until roads clear (48-72 hrs)",
        additionalCostPercent: 3,
        additionalDelayDays: 3,
        routeType: "ground",
      },
      {
        description: "Reroute via southern corridor (I-40)",
        additionalCostPercent: 25,
        additionalDelayDays: 2,
        routeType: "ground",
      },
    ],
    promptTemplate:
      "A severe winter storm is forecast to hit the Midwest over the next 48 hours. Blizzard conditions expected from Chicago through St. Louis with highway closures likely. What is our risk exposure?",
  },
  {
    id: "parts-shortage",
    name: "Semiconductor Shortage",
    description:
      "Critical semiconductor shortage affecting server and networking equipment production. Major suppliers have notified of 8-12 week lead time extensions for GPUs, custom ASICs, and advanced processors.",
    icon: "\u{1F527}",
    affectedRegion: {
      center: { lat: 25.0, lng: 121.0, label: "Taiwan/Global" },
      radiusKm: 50,
    },
    affectedRouteSegments: [
      "semiconductor",
      "gpu-supply",
      "asic-supply",
      "processor-supply",
    ],
    severityMultiplier: 2.0,
    estimatedDelayDays: 60,
    alternativeRoutes: [
      {
        description: "Source alternative components from secondary suppliers",
        additionalCostPercent: 40,
        additionalDelayDays: 21,
        routeType: "air",
      },
      {
        description: "Negotiate priority allocation with existing suppliers",
        additionalCostPercent: 15,
        additionalDelayDays: 14,
        routeType: "air",
      },
    ],
    promptTemplate:
      "Our suppliers have notified us of a critical semiconductor shortage affecting server and networking equipment production. Lead times are extending by 8-12 weeks. Which client projects are at risk?",
  },
];
